{"name": "Unsuccessful login with invalid credentials -- @1.1 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x000000010d8f8b88 chromedriver + 5860232\n1   chromedriver                        0x000000010d8f012a chromedriver + 5824810\n2   chromedriver                        0x000000010d3c7e20 chromedriver + 417312\n3   chromedriver                        0x000000010d419cab chromedriver + 752811\n4   chromedriver                        0x000000010d419ec1 chromedriver + 753345\n5   chromedriver                        0x000000010d469dc4 chromedriver + 1080772\n6   chromedriver                        0x000000010d43fd1d chromedriver + 908573\n7   chromedriver                        0x000000010d467169 chromedriver + 1069417\n8   chromedriver                        0x000000010d43fac3 chromedriver + 907971\n9   chromedriver                        0x000000010d40c107 chromedriver + 696583\n10  chromedriver                        0x000000010d40cd71 chromedriver + 699761\n11  chromedriver                        0x000000010d8b6ca0 chromedriver + 5590176\n12  chromedriver                        0x000000010d8bacf9 chromedriver + 5606649\n13  chromedriver                        0x000000010d8920b6 chromedriver + 5439670\n14  chromedriver                        0x000000010d8bb66f chromedriver + 5609071\n15  chromedriver                        0x000000010d880e64 chromedriver + 5369444\n16  chromedriver                        0x000000010d8dd688 chromedriver + 5748360\n17  chromedriver                        0x000000010d8dd850 chromedriver + 5748816\n18  chromedriver                        0x000000010d8efcc1 chromedriver + 5823681\n19  libsystem_pthread.dylib             0x00007fff208b58fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff208b1443 thread_start + 15\n\n", "trace": "  File \"/Users/macbookpro/Downloads/Task18_BDDpython/.venv/lib/python3.13/site-packages/behave/model.py\", line 1991, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/steps_login.py\", line 10, in step_open_login\n    context.login_page.open()\n    ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/pages/login_page.py\", line 29, in open\n    self.wait.until(EC.visibility_of_element_located(self.USERNAME))\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/.venv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given browser is launched and Zen login page is opened", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x000000010d8f8b88 chromedriver + 5860232\n1   chromedriver                        0x000000010d8f012a chromedriver + 5824810\n2   chromedriver                        0x000000010d3c7e20 chromedriver + 417312\n3   chromedriver                        0x000000010d419cab chromedriver + 752811\n4   chromedriver                        0x000000010d419ec1 chromedriver + 753345\n5   chromedriver                        0x000000010d469dc4 chromedriver + 1080772\n6   chromedriver                        0x000000010d43fd1d chromedriver + 908573\n7   chromedriver                        0x000000010d467169 chromedriver + 1069417\n8   chromedriver                        0x000000010d43fac3 chromedriver + 907971\n9   chromedriver                        0x000000010d40c107 chromedriver + 696583\n10  chromedriver                        0x000000010d40cd71 chromedriver + 699761\n11  chromedriver                        0x000000010d8b6ca0 chromedriver + 5590176\n12  chromedriver                        0x000000010d8bacf9 chromedriver + 5606649\n13  chromedriver                        0x000000010d8920b6 chromedriver + 5439670\n14  chromedriver                        0x000000010d8bb66f chromedriver + 5609071\n15  chromedriver                        0x000000010d880e64 chromedriver + 5369444\n16  chromedriver                        0x000000010d8dd688 chromedriver + 5748360\n17  chromedriver                        0x000000010d8dd850 chromedriver + 5748816\n18  chromedriver                        0x000000010d8efcc1 chromedriver + 5823681\n19  libsystem_pthread.dylib             0x00007fff208b58fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff208b1443 thread_start + 15\n\n", "trace": "  File \"/Users/macbookpro/Downloads/Task18_BDDpython/.venv/lib/python3.13/site-packages/behave/model.py\", line 1991, in run\n    match.run(runner.context)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/.venv/lib/python3.13/site-packages/behave/matchers.py\", line 105, in run\n    self.func(context, *args, **kwargs)\n    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"features/steps/steps_login.py\", line 10, in step_open_login\n    context.login_page.open()\n    ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/pages/login_page.py\", line 29, in open\n    self.wait.until(EC.visibility_of_element_located(self.USERNAME))\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/.venv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Open Zen login page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n0   chromedriver                        0x000000010d8f8b88 chromedriver + 5860232\n1   chromedriver                        0x000000010d8f012a chromedriver + 5824810\n2   chromedriver                        0x000000010d3c7e20 chromedriver + 417312\n3   chromedriver                        0x000000010d419cab chromedriver + 752811\n4   chromedriver                        0x000000010d419ec1 chromedriver + 753345\n5   chromedriver                        0x000000010d469dc4 chromedriver + 1080772\n6   chromedriver                        0x000000010d43fd1d chromedriver + 908573\n7   chromedriver                        0x000000010d467169 chromedriver + 1069417\n8   chromedriver                        0x000000010d43fac3 chromedriver + 907971\n9   chromedriver                        0x000000010d40c107 chromedriver + 696583\n10  chromedriver                        0x000000010d40cd71 chromedriver + 699761\n11  chromedriver                        0x000000010d8b6ca0 chromedriver + 5590176\n12  chromedriver                        0x000000010d8bacf9 chromedriver + 5606649\n13  chromedriver                        0x000000010d8920b6 chromedriver + 5439670\n14  chromedriver                        0x000000010d8bb66f chromedriver + 5609071\n15  chromedriver                        0x000000010d880e64 chromedriver + 5369444\n16  chromedriver                        0x000000010d8dd688 chromedriver + 5748360\n17  chromedriver                        0x000000010d8dd850 chromedriver + 5748816\n18  chromedriver                        0x000000010d8efcc1 chromedriver + 5823681\n19  libsystem_pthread.dylib             0x00007fff208b58fc _pthread_start + 224\n20  libsystem_pthread.dylib             0x00007fff208b1443 thread_start + 15\n\n", "trace": "  File \"features/steps/steps_login.py\", line 10, in step_open_login\n    context.login_page.open()\n    ~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/pages/login_page.py\", line 29, in open\n    self.wait.until(EC.visibility_of_element_located(self.USERNAME))\n    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/macbookpro/Downloads/Task18_BDDpython/.venv/lib/python3.13/site-packages/selenium/webdriver/support/wait.py\", line 138, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "attachments": [{"name": "page_source", "source": "c8f4b5dc-280b-40cc-8255-26802301530e-attachment.html", "type": "text/html"}], "start": 1757004731254, "stop": 1757004743938}], "start": 1757004731254, "stop": 1757004743940}, {"name": "When I login with username \"wrong@user.com\" and password \"wrongPass\"", "status": "skipped", "start": 1757004743942, "stop": 1757004743942}, {"name": "Then I should see a login error message", "status": "skipped", "start": 1757004743942, "stop": 1757004743942}], "parameters": [{"name": "username", "value": "wrong@user.com"}, {"name": "password", "value": "wrongPass"}], "start": 1757004731253, "stop": 1757004743942, "uuid": "d8b7fbec-dfc0-4fa4-aae8-6861fff85b4b", "historyId": "625a8ba02d89779882dab18a83e28604", "fullName": "Zenclass Login and Logout validations using POM + Behave + Allure: Unsuccessful login with invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "negative"}, {"name": "feature", "value": "Zenclass Login and Logout validations using POM + Behave + Allure"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}], "titlePath": ["features", "Zenclass Login and Logout validations using POM + Behave + Allure"]}